### ISSUE TITLE
Bug: Update check fails

### ISSUE THREAD

**Issue by tjsuominen** [basildane/WakeOnLAN#121]
In the Help > "About" dialog, the automatic update check (I have the preference "True" on in the settings) fails every time with error (visible only partial):

**"The underlying connection was closed: An unexp"** and that's all whats visible.

My internet connection is working perfectly (web, mails...) but this error has recently occurred. It happens every time I click on the Help > "About".

The only thing what I have changed in my W10 (Pro, 64-bit) configuration, is the new DNS provider to 1.1.1.1 (more info @ https://1.1.1.1/). I'm running W10 64-bit Pro 1803 (not yet updated to 1809). Other apps (e.g. Total Commander, Paint.net etc.) perform update their update checks OK.

**What could cause this?** I have no other firewall etc. than the one with Windows Defender 10 (and haven't changed there anything for months).

![wol](https://user-images.githubusercontent.com/7660277/46519790-514b6780-c882-11e8-9f6b-0f4b77e1e668.jpg)

//Timo

**Comment by basildane** [comment]
Thanks for reporting it.  It is now fixed.

Long story:
The problem was a TLS issue on the firewall in front of the updates.  I will need to add support for TLS 1.2 on the WOL client in the next release as a security enhancement.  In the meantime, I restored the TLS 1.0 service for updates so you will not get an error.

**Comment by tjsuominen** [comment]
Appreciated, thx :)
