### ISSUE TITLE
WOL stucked in command line

### ISSUE THREAD

**Issue by CPAM84** [basildane/WakeOnLAN#157]
Hello,
 
 I'm using your tool to wake up all our computers in command line, with something like that:
  "C:\Program Files\Aquila Technology\WakeOnLAN\WakeOnLANc.exe" -p "C:\ProgramData\Aquila Technology\WakeOnLan\machines.xml" -w -all
 
 The problem is that the program get stucked on some computer for any reason and won't try to continue waking up the rest.
 Every machine is configured with TTl=128 and repeat=1. Is there any way to set some kind of timeout so the program keeps going after failing to wake up a machine?
  
 I gave a quick look to the code and I think this is caused by the SyncLock statement in Wake.vb in function WakeUp, but I'm not sure.
 What is the purpose of that SyncLock?
 
 Thanks in advance for your answer!

**Comment by basildane** [comment]
The Synclock is in the GUI WakeOnLan code, to prevent the function from being called out of order by the GUI.  This is not the wakeup function you are calling because you are using the command line.  You want to look at WakeUp in the WakeOnLanC project.

I'm looking at the code and I don't see how this problem could occur, as it sends a batch of wake broadcasts.  It is never waiting for a response to hang up on, as there is no response to that kind of message.  Just a wild guess, but are some of your clients on an invalid subnet?

**Comment by basildane** [comment]
Please enable logging (Tools / Trace Log).
Then run your command again, see if it captures anything in My Documents/Wakeonlan.tracelog.
You can upload that file to me here: [Upload Log](https://cloud.aquilatech.com/s/cKHVPHPXfaYdbjn)
I don't know if it will help but it's a start.

**Comment by CPAM84** [comment]
Thanks for your answer.
It happened with machines on the same subnet as the one running the program and the broadcast address looks correct in the conf file.
I'll launch another test with logging enabled next week.

**Comment by CPAM84** [comment]
I tried again twice and this time it worked perfectly fine.
I guess something else on the server was bugging, I don't know what yet.
Thanks again.
