### ISSUE TITLE
Schedule WOL without userid and password?

### ISSUE THREAD

**Issue by RuudB123** [basildane/WakeOnLAN#35]
Hi All,

I have a problem to schedule WOL using WakeOnLAN tool. When I try to configure it, I Always receive this message 'Register Task Definition - UserID'. Maybe it's related to the domain\userid and password. But I don't know what to enter here.

I'm trying to start a laptop automatically that will show a presentation using WOL. When I wake up the laptop manually using WakeOnLAN tool, it's working fine.
Both laptops are connected wired and in the same network. But no domain configured, just a workgroup called WORKGROUP.

Please advise,

BR,

Ruud

**Comment by basildane** [comment]
WOL uses the Windows task scheduler.
In order to schedule some kinds of events, Windows requires that scheduled tasks run under a user account.  That's what it is asking for here.  If you want, you can enter the user account that you are logged into Windows with.

Some other users may want to have a "service account" with specific user rights specifically setup to do remote shutdowns...

Since you are in a workgroup, I think the syntax is machineName\user.

**Comment by RuudB123** [comment]
Thanks Basildane, That works perfect!! The syntax was machinename\username.
Now my laptop starts automatically every workday.
Thanks!

BR,

Ruud

**Comment by basildane** [comment]
Great.  Thanks for letting me know you got it working!
