### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Niteowlpc** [basildane/WakeOnLAN#89]
Has anyone ever requested that you add a way to send a message to workstations? The program already sends a warning message when the system is shutting down. I have been looking for a reliable, lightweight app that will send a simple popup message to a workstation. It would be nice if an app that I already use would do this.

**Comment by basildane** [comment]
Yes, this has been an extremely troublesome feature.  I've used several different methods to try and send messages.  It's not completely reliable because of differences in operating systems and local network policies.

So, you are asking that you could right-click a host and send a message?  Do I understand correctly?

Also, does the current messaging system that WOL uses work in your environment?

**Comment by Niteowlpc** [comment]
Yes, that is what I was requesting. Being able to right click a host and send a message. It does currently work in my environment, if I shut down a computer that has a user logged on, it sends them a warning message before shutting down.

**Comment by basildane** [comment]
That should be an easy one.  I could use that feature too.

**Comment by basildane** [comment]
Do you use shutdown-method "WMI" or "Legacy"?

**Comment by Niteowlpc** [comment]
WMI

**Comment by basildane** [comment]
Please try [2.11.19 beta 40](https://cloud.aquilatech.com/s/FzZ4tFKAX1YSv3w).
It's not signed, I don't have my signing key with me today.  But do let me know if this does what you are looking for.
